version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8003:8003"  # Exposing FastAPI on port 8003
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fastapi_db
      DB_USER: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"  # Mapping Postgres internal 5432 to external 5434
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
